// ─────────────────────────────────────────────────────────────────────
// The Calendar copy, in English. Same keys as calendario.pt.ts — copy.ts
// makes TypeScript refuse anything else.
// ─────────────────────────────────────────────────────────────────────

export const CALENDARIO_EN = {
  lead: 'Book a 30-minute conversation with me. Sign in with your email — you get a code, no password — and pick a free time. Times show in your own timezone.',
  month: 'Month',
  day: 'Day',
  today: 'Today',
  prev: 'Previous month',
  next: 'Next month',
  free: 'free',
  frees: 'free',
  nothing: 'Nothing booked on this day.',
  now: 'Now',
  signIn: 'Sign in',
  signInHint: 'Only signed-in people see availability. The link goes to your email; there is no password.',
  signInGoogle: 'Continue with Google',
  signInOr: 'or',
  email: 'Email',
  sendLink: 'Send link',
  linkSent: 'We sent a link to',
  linkHint: 'Open it in your email to sign in. Valid for ten minutes, and closes itself once you are in.',
  resend: 'Send again',
  signedAs: 'Signed in as',
  signOut: 'Sign out',
  bookTitle: 'New meeting',
  titleLabel: 'Subject',
  titlePlaceholder: 'What you want to talk about',
  noteLabel: 'Notes',
  notePlaceholder: 'Context, links, whatever helps.',
  confirm: 'Book',
  cancel: 'Cancel',
  close: 'Close',
  mine: 'Your meetings',
  none: 'Nothing booked yet.',
  cancelMeeting: 'Cancel meeting',
  cancelled: 'Meeting cancelled.',
  booked: 'Booked. I sent you a confirmation by email.',
  sending: 'Sending…',
  tz: 'Local time',
  minutes: 'min',
  busy: 'Busy',
  meeting: 'Meeting',
  meetings: 'meetings',
  meetingOne: 'meeting',
  who: 'With',
  details: 'Meeting details',

  // ── Owner only ───────────────────────────────────────────────────
  block: 'Block',
  opening: 'Opening',
  newBlock: 'New block or opening',
  kindLabel: 'Kind',
  startLabel: 'Start',
  endLabel: 'End',
  blockNote: 'Reason',
  blockNotePlaceholder: 'Holiday, travel, a busy morning.',
  create: 'Create',
  remove: 'Remove',
  blockCreated: 'Availability updated.',
  blockRemoved: 'Change removed.',

  errors: {
    email: 'That email does not look right.',
    link: 'That link is no longer valid. Ask for a new one.',
    limit: 'Too many attempts. Wait a bit.',
    taken: 'That time is no longer free.',
    off: 'Booking is switched off right now. Email me instead.',
    proprio: 'This diary is yours — you do not book a call with yourself. Create a block instead.',
    owner: 'This is only for the calendar owner.',
    interval: 'The end has to come after the start.',
    generic: 'That did not work. Try again.',
  },
};
