// ─────────────────────────────────────────────────────────────────────
// Todo o texto do site em português.
//
// Uma língua, um ficheiro. As duas têm exactamente as mesmas chaves — o
// TypeScript garante-o em copy.ts, onde as duas se juntam: mudar uma
// chave só num dos lados deixa de compilar.
// ─────────────────────────────────────────────────────────────────────

export const PT = {
  htmlLang: 'pt-PT',
  locale: 'pt_PT',
  intlLocale: 'pt-PT',
  title: 'Hélder Gonçalves — Engenheiro de software e IA',
  description:
    'Engenheiro de software em Barcelos, Portugal. Construo produtos e ferramentas com modelos de linguagem, agentes e automação — e escrevo sobre isso. O site é um sistema operativo: no telemóvel um iPhone, no computador um Mac.',
  keywords:
    'engenheiro de software, developer, inteligência artificial, agentes de IA, LLM, MCP, automação, TypeScript, Python, Portugal, Barcelos, blog',
  role: 'Engenheiro de software',
  place: 'Barcelos, Portugal',
  skip: 'Saltar para o conteúdo',
  switch: 'English',
  footer: 'Feito com Astro, sem frameworks e sem cookies.',

  intro:
    'Sou o Hélder. Construo software — e, cada vez mais, software com modelos de linguagem lá dentro: agentes, servidores MCP e automação que poupa trabalho a quem o faz.',
  intro2:
    'De dia trabalho na Bitsapiens, em sistemas que ligam pessoas, dados e IA. De noite ando pelos meus projetos: um servidor MCP que lê a app Stocks do macOS, uma ponte para pilotar o Claude Code a partir de um Garmin, um bot que transforma conversa de comunidade em backlog. Quase tudo em código aberto.',
  intro3:
    'Prefiro entregas pequenas e frequentes a planos grandes. Aqui escrevo o que aprendo pelo caminho — sem cerimónia, sem newsletter, sem cookies.',

  // ── O sistema ───────────────────────────────────────────
  os: {
    macName: 'helderOS',
    phoneName: 'iHelder',
    booting: 'A arrancar',
    greeting: 'Olá',
    unlock: 'Deslizar para abrir',
    unlockShort: 'Deslizar',
    lockHint: 'Toca ou desliza para cima',
    welcome: 'Bem-vindo',
    openApp: 'Abrir',
    close: 'Fechar',
    aboutApp: 'Acerca de %s',
    minimize: 'Minimizar',
    zoom: 'Ecrã inteiro',
    back: 'Voltar',
    done: 'Concluído',
    search: 'Pesquisar',
    searchHint: '↩ para abrir · esc para fechar',
    searchApps: 'Aplicações',
    searchPosts: 'Blog',
    searchLinks: 'Ligações',
    searchEmpty: 'Sem resultados',
    noWindows: 'Nenhuma janela aberta. Escolhe uma aplicação na Dock.',
    trash: 'Reciclagem',
    trashEmpty: 'A Reciclagem está vazia. Como deve ser.',
    desktopHd: 'Disco de Hélder',
    desktopCv: 'Currículo.pdf',
    hintMac: 'Arrasta as janelas · ⌘K para pesquisar',
    hintPhone: 'Toca num ícone · desliza para cima para voltar',
    appSwitcher: 'Aplicações abertas',
    notifications: 'Notificações',
    wallpaperNames: { aurora: 'Aurora', sonoma: 'Serra', night: 'Noite', graphite: 'Grafite' },
    today: 'Hoje',
    menus: {
      apple: [
        { label: 'Sobre este Mac', action: 'open:sobre' },
        { label: 'Definições do Sistema…', action: 'open:definicoes' },
        { label: '—', action: '' },
        { label: 'Escrever ao Hélder…', action: 'mail' },
        { label: 'GitHub', action: 'link:github' },
        { label: '—', action: '' },
        { label: 'Reiniciar…', action: 'restart' },
      ],
      file: [
        { label: 'Abrir…', action: 'spotlight', key: '⌘O' },
        { label: '—', action: '' },
        { label: 'Fechar janela', action: 'close', key: '⌘W' },
        { label: 'Fechar tudo', action: 'closeAll', key: '⌥⌘W' },
      ],
      edit: [
        { label: 'Copiar ligação', action: 'copy', key: '⇧⌘C' },
        { label: 'Partilhar…', action: 'share' },
        { label: '—', action: '' },
        { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
      ],
      view: [
        { label: 'Mudar o tema', action: 'theme' },
        { label: 'Mudar o fundo', action: 'wallpaper:next' },
        { label: '—', action: '' },
        { label: 'Ecrã inteiro', action: 'zoom', key: '⌃⌘F' },
      ],
      window: [
        { label: 'Minimizar', action: 'minimize', key: '⌘M' },
        { label: 'Ecrã inteiro', action: 'zoom' },
        { label: 'Fechar janela', action: 'close', key: '⌘W' },
        { label: '—', action: '' },
        { label: 'Aplicações abertas…', action: 'switcher', key: '⌘⇥' },
        { label: 'Arrumar janelas', action: 'tile' },
        { label: 'Fechar tudo', action: 'closeAll' },
      ],
      help: [
        { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
        { label: 'Mudar para inglês', action: 'lang' },
        { label: 'Mudar o tema', action: 'theme' },
        { label: '—', action: '' },
        { label: 'Como isto foi feito', action: 'open:sobre' },
      ],
    },
    menuLabels: { file: 'Ficheiro', edit: 'Editar', view: 'Ver', window: 'Janela', help: 'Ajuda' },
    copied: 'Ligação copiada',
    control: {
      title: 'Central de Controlo',
      theme: 'Aparência',
      light: 'Claro',
      dark: 'Escuro',
      wallpaper: 'Fundo',
      lang: 'Idioma',
      brightness: 'Brilho',
      focus: 'Concentração',
      focusOn: 'Só o essencial',
      airplane: 'Modo avião',
      wifi: 'Wi‑Fi',
      offline: 'Sem rede — o site continua a funcionar.',
    },
    battery: 'Bateria',
    wifi: 'Wi‑Fi',
  },

  // ── Aplicações ──────────────────────────────────────────
  apps: {
    sobre: { name: 'Perfil', subtitle: 'Quem escreve isto', window: 'Perfil' },
    escritos: { name: 'Blog', subtitle: 'Notas sobre o que construo', window: 'Blog' },
    mensagens: { name: 'Mensagens', subtitle: 'Perguntas rápidas', window: 'Mensagens' },
    contacto: { name: 'Mail', subtitle: 'Falar comigo', window: 'Nova mensagem' },
    projetos: { name: 'Projetos', subtitle: 'O que ando a construir', window: 'Projetos' },
    terminal: { name: 'Terminal', subtitle: 'Para quem gosta de teclado', window: 'helder — zsh' },
    definicoes: { name: 'Definições', subtitle: 'Tema, idioma e fundo', window: 'Definições' },
    simulador: { name: 'Simulador', subtitle: 'Um iPhone dentro do site', window: 'Simulador — iPhone' },
  },

  sobre: {
    lead: 'Engenheiro de software em Barcelos. Construo produtos com modelos de linguagem lá dentro.',
    specs: 'Especificações',
    specRole: 'Função',
    specPlace: 'Localização',
    specCompany: 'Empresa',
    specStack: 'Ferramentas',
    specStackValue: 'TypeScript · Python · Astro · Docker · Postgres · MCP',
    specSince: 'A programar desde',
    specSinceValue: 'sempre que houve teclado por perto',
    more: 'Mais sobre este site',
    colophon:
      'Este site é um sistema operativo. No telemóvel comporta-se como um iPhone, no computador como um Mac — janelas que se arrastam, uma Dock que aumenta, uma Central de Controlo que funciona a sério. Está feito em Astro, HTML e CSS, com JavaScript escrito à mão e zero frameworks. Todo o texto que aqui está é HTML normal por baixo: funciona sem JavaScript e o Google lê-o na mesma.',
    buttonWrite: 'Escrever-me',
    buttonProjects: 'Ver projetos',
  },

  escritos: {
    heading: 'Blog',
    title: 'Blog',
    description:
      'Notas de Hélder Gonçalves sobre engenharia de software, modelos de linguagem, agentes, MCP e automação.',
    lead: 'Notas sobre engenharia, modelos de linguagem e as ferramentas que construo. Sem calendário fixo — só quando há alguma coisa que valha a pena dizer.',
    empty: 'Ainda nada publicado. Está a caminho.',
    pick: 'Escolhe um escrito à esquerda.',
    feed: 'Assinar por RSS',
    all: 'Todo o blog',
    count: 'escritos',
    readingTime: 'min de leitura',
    search: 'Pesquisar',
    noMatch: 'Sem resultados',
    compose: 'Escrever ao Hélder',
    share: 'Partilhar',
    sidebar: 'Mostrar ou ocultar a lista',
    updated: 'Atualizado a',
    readOther: 'Read this in English',
    tags: 'Temas',
    talk: 'Discordas ou queres continuar a conversa?',
    talkLink: 'Escreve-me.',
    backToList: '← Blog',
    subscribeTitle: 'Receber os escritos',
    subscribeLabel: 'O teu email',
    subscribePlaceholder: 'o-teu@email.pt',
    subscribeAction: 'Subscrever',
    subscribeNote: 'Um email quando houver escrito novo. Mais nada, e sais quando quiseres.',
    subscribeSending: 'A enviar…',
    subscribeSent: 'Está quase: confirma na ligação que te enviei por email.',
    subscribeBad: 'Esse email não parece estar certo.',
    subscribeFail: 'Não deu. Tenta outra vez daqui a bocado.',
    subscribeOff: 'A subscrição está desligada de momento.',
  },

  contacto: {
    lead: 'A forma mais rápida é o email. Respondo a tudo o que tenha contexto.',
    to: 'Para',
    from: 'De',
    subject: 'Assunto',
    subjectValue: 'Olá Hélder',
    body: 'Mensagem',
    placeholder: 'Escreve aqui. Ao enviar, isto abre o teu email com tudo já preenchido — não há servidor nenhum a guardar nada.',
    send: 'Enviar',
    sendHint: 'Abre a tua aplicação de email',
    elsewhere: 'Noutros sítios',
    copied: 'Email copiado',
    copy: 'Copiar email',
    sending: 'A enviar…',
    sent: 'Mensagem enviada. Obrigado — respondo em breve.',
    failed: 'Não consegui enviar daqui. Abri a tua aplicação de email.',
    limit: 'Já foram muitas mensagens deste sítio. Tenta daqui a pouco.',
    invalid: 'Falta um email válido para eu poder responder.',
    short: 'Escreve um pouco mais — dá-me contexto.',
    honeypot: 'Deixa este campo vazio',
  },

  projetos: {
    lead: 'Coisas que construí porque me faziam falta. Quase tudo em código aberto.',
    open: 'Abrir no GitHub',
    all: 'Ver tudo no GitHub',
    list: [
      {
        name: 'MCP para a app Stocks',
        tagline: 'O Claude a ler a minha carteira',
        body: 'Um servidor MCP que lê a base de dados local da aplicação Stocks do macOS e devolve as carteiras e cotações a qualquer modelo. Sem API paga, sem scraping: os dados já estavam no disco.',
        tags: ['MCP', 'Swift', 'macOS'],
      },
      {
        name: 'Garmin → Claude Code',
        tagline: 'Pilotar o portátil a partir da bicicleta',
        body: 'Uma ponte que transforma o ciclocomputador Garmin num controlo remoto do Claude Code: lanço tarefas, recebo o resultado no ecrã do guiador. Nasceu de uma piada e ficou a funcionar.',
        tags: ['Garmin', 'TypeScript', 'Agentes'],
      },
      {
        name: 'Conversa → backlog',
        tagline: 'Comunidade que se transforma em produto',
        body: 'Um bot que lê a conversa de uma comunidade, percebe o que são pedidos reais e escreve issues limpas com contexto e prioridade. Menos "alguém tinha dito isto no Discord".',
        tags: ['LLM', 'Python', 'Automação'],
      },
      {
        name: 'Este site',
        tagline: 'Um sistema operativo em 60 KB',
        body: 'O que estás a ver. Astro para o conteúdo, JavaScript à mão para as janelas, a Dock, os gestos e o telefone dentro do telefone. Sem React, sem bibliotecas de animação, sem tracking.',
        tags: ['Astro', 'CSS', 'Sem frameworks'],
      },
    ],
  },

  mensagens: {
    lead: 'Perguntas rápidas, respostas rápidas.',
    contactName: 'Hélder',
    status: 'normalmente responde no mesmo dia',
    placeholder: 'Escolhe uma pergunta…',
    input: 'Escreve uma mensagem…',
    send: 'Enviar',
    ai: 'Respostas geradas por IA, a partir do que está neste site.',
    aiOff: 'Respostas guardadas. Para falar a sério, escreve-me por email.',
    error: 'Não consegui responder agora. Tenta outra vez, ou escreve-me por email.',
    limit: 'Já falámos bastante por hoje. Escreve-me por email que respondo eu.',
    unknown: 'Sobre isso é melhor perguntares-me diretamente: helder@heldergoncalves.io',
    typing: 'a escrever…',
    delivered: 'Entregue',
    restart: 'Recomeçar',
    opener: 'Olá! Isto sou eu em versão automática. Pergunta o que quiseres — ou escreve-me a sério pelo email.',
    chat: [
      {
        q: 'O que fazes exatamente?',
        a: 'Construo software com modelos de linguagem lá dentro: agentes que fazem trabalho a sério, servidores MCP que ligam modelos a dados que já existem, e automação que tira tarefas chatas das mãos das pessoas.',
      },
      {
        q: 'Estás disponível para trabalhar?',
        a: 'De dia estou na Bitsapiens. Fora disso ouço sempre projetos com prazo realista e problema interessante — sobretudo se envolver agentes, dados ou produto do zero.',
      },
      {
        q: 'Que ferramentas usas?',
        a: 'TypeScript e Python para quase tudo. Astro para sites, Docker e Coolify para pôr no ar, Postgres quando há dados a sério. E muito Claude Code — passei a escrever menos código à mão e a rever muito mais.',
      },
      {
        q: 'Como é que este site foi feito?',
        a: 'Astro gera HTML estático e o resto é JavaScript escrito à mão: janelas que se arrastam, Dock com ampliação, gestos do telefone. Zero frameworks. Abre o Terminal e escreve "sobre" se quiseres os detalhes.',
      },
      {
        q: 'Onde é que escreves?',
        a: 'Aqui mesmo, na aplicação Blog. Há feed RSS e não há newsletter — prefiro que venhas quando te apetecer.',
      },
      {
        q: 'Posso mandar-te um email?',
        a: 'Claro. helder@heldergoncalves.io — respondo a tudo o que traga contexto. Abre a app Contacto que já vai preenchido.',
      },
    ],
  },

  definicoes: {
    appearance: 'Aparência',
    appearanceHint: 'Claro, escuro ou o que o teu sistema pedir.',
    auto: 'Automático',
    light: 'Claro',
    dark: 'Escuro',
    wallpaper: 'Fundo',
    wallpaperHint: 'Escolhe o ambiente. Fica guardado neste dispositivo.',
    language: 'Idioma',
    languageHint: 'Muda o site inteiro, incluindo os escritos.',
    motion: 'Animações',
    motionHint: 'Desliga as transições se preferires o site quieto.',
    motionOn: 'Ligadas',
    motionOff: 'Reduzidas',
    sound: 'Som',
    soundHint: 'Cliques discretos ao abrir e fechar aplicações.',
    reset: 'Repor tudo',
    resetHint: 'Volta ao estado de fábrica e recarrega.',
    about: 'Sobre este sistema',
    version: 'Versão',
    legal: 'Aviso',
    legalText:
      'Site pessoal, sem fins comerciais, sem publicidade e sem receita. Homenagem aos sistemas da Apple — sem qualquer ligação à Apple Inc. Nenhum ficheiro da Apple é usado aqui: os ícones são do Lucide (ISC) e a tipografia, fora dos dispositivos Apple, é a Inter (OFL). Apple, iPhone e macOS são marcas da Apple Inc.',
    wallpapers: {
      aurora: 'Aurora',
      sonoma: 'Serra',
      night: 'Noite',
      graphite: 'Grafite',
    },
  },

  terminal: {
    welcome: 'Escreve "ajuda" para ver o que isto faz.',
    unknown: 'comando não encontrado:',
    hint: 'Sugestão:',
    help: [
      ['ajuda', 'esta lista'],
      ['sobre', 'quem sou eu'],
      ['escritos', 'listar os escritos'],
      ['ler <n>', 'abrir o escrito número n'],
      ['projetos', 'o que ando a construir'],
      ['contacto', 'como falar comigo'],
      ['abrir <app>', 'abrir uma aplicação'],
      ['tema claro|escuro', 'mudar a aparência'],
      ['idioma pt|en', 'mudar de língua'],
      ['data', 'que dia é hoje'],
      ['neofetch', 'as specs desta máquina'],
      ['limpar', 'limpar o ecrã'],
    ],
    sudo: 'Boa tentativa. Este utilizador não está na lista de sudoers — o incidente vai ser reportado.',
    openedApp: 'a abrir',
    noApp: 'não há aplicação com esse nome.',
    noPost: 'não há escrito com esse número.',
  },

  notFound: {
    title: 'Página não encontrada',
    lead: 'Este endereço não existe — ou já não existe.',
    home: 'Ir para o início',
    blog: 'Ver os escritos',
    code: 'Erro 404',
    dialog: 'A aplicação não pode ser aberta porque o ficheiro não foi encontrado.',
    ok: 'OK',
  },

  labels: { github: 'GitHub', linkedin: 'LinkedIn', twitter: 'X', email: 'Email', rss: 'RSS' },
};
