// ─────────────────────────────────────────────────────────────────────
// Todo o texto do site em inglês.
//
// Uma língua, um ficheiro. As duas têm exactamente as mesmas chaves — o
// TypeScript garante-o em copy.ts, onde as duas se juntam: mudar uma
// chave só num dos lados deixa de compilar.
// ─────────────────────────────────────────────────────────────────────

import { OS_EN } from './os.en';

export const EN = {
  htmlLang: 'en',
  locale: 'en_GB',
  intlLocale: 'en-GB',
  title: 'Hélder Gonçalves — Software & AI engineer',
  description:
    'Software engineer based in Barcelos, Portugal. I build products and tools around language models, agents and automation — and I write about it. This site is an operating system: an iPhone on mobile, a Mac on desktop.',
  keywords:
    'software engineer, developer, artificial intelligence, AI agents, LLM, MCP, automation, TypeScript, Python, Portugal, blog',
  role: 'Software engineer',
  place: 'Barcelos, Portugal',
  skip: 'Skip to content',
  switch: 'Português',
  footer: 'Built with Astro, no frameworks and no cookies.',

  intro:
    "I'm Hélder. I build software — and, more and more, software with language models inside it: agents, MCP servers, and automation that saves real people real work.",
  intro2:
    'By day I work at Bitsapiens on systems that connect people, data and AI. The rest of the time I build my own things: an MCP server that reads the macOS Stocks app, a bridge to steer Claude Code from a Garmin bike computer, a bot that turns community chat into a product backlog. Almost all of it open source.',
  intro3:
    'I prefer small frequent deliveries to big plans. This is where I write down what I learn along the way — no ceremony, no newsletter, no cookies.',

  os: OS_EN,

  apps: {
    sobre: { name: 'Profile', subtitle: 'Who writes this', window: 'Profile' },
    escritos: { name: 'Blog', subtitle: 'Notes on what I build', window: 'Blog' },
    mensagens: { name: 'Messages', subtitle: 'Quick questions', window: 'Messages' },
    contacto: { name: 'Mail', subtitle: 'Get in touch', window: 'New message' },
    projetos: { name: 'Projects', subtitle: 'What I am building', window: 'Projects' },
    terminal: { name: 'Terminal', subtitle: 'For keyboard people', window: 'helder — zsh' },
    definicoes: { name: 'Settings', subtitle: 'Theme, language, wallpaper', window: 'Settings' },
    bolsa: { name: 'Stocks', subtitle: 'Live quotes', window: 'Stocks' },
    calendario: { name: 'Calendar', subtitle: 'Book a conversation with me', window: 'Calendar' },
    simulador: { name: 'Simulator', subtitle: 'An iPhone inside the site', window: 'Simulator — iPhone' },
  },

  bolsa: {
    lead: 'Live quotes, like the Stocks app. The list is yours: add and remove symbols, and it stays on this device.',
    list: 'Watchlist',
    portfolio: 'Portfolio',
    portfolioLead: "Hélder's portfolio. The holdings stay on this device — no one sees them but whoever types them in.",
    add: 'Add symbol',
    addPlaceholder: 'Name or symbol',
    searching: 'Searching…',
    searchEmpty: 'No results.',
    remove: 'Remove',
    edit: 'Edit',
    done: 'Done',
    loading: 'Loading…',
    unavailable: 'No quotes right now. Try again in a moment.',
    notFound: 'Could not find that symbol.',
    ranges: { '1d': '1D', '1w': '1W', '1m': '1M', '3m': '3M', '6m': '6M', ytd: 'YTD', '1y': '1Y', '2y': '2Y', '5y': '5Y' },
    previous: 'Previous close',
    currency: 'Currency',
    market: 'Market',
    marketOpen: 'Open',
    marketClosed: 'Closed',
    updated: 'Updated at',
    pick: 'Pick a symbol from the list.',
    live: 'Refreshes every 30 seconds while open.',
    source: 'Data from Yahoo Finance, delayed as usual. Not advice.',
    empty: 'The list is empty. Add a symbol.',
    stats: {
      open: 'Open', high: 'High', low: 'Low', high52: '52 Wk High', low52: '52 Wk Low',
      marketCap: 'Mkt Cap', pe: 'P/E Ratio', yield: 'Div Yield', avgVolume: 'Avg Volume',
    },
    about: 'About',
    sector: 'Sector',
    visitWebsite: 'Visit Website',
    news: 'News',
    newsEmpty: 'No news for this symbol.',
    shares: 'Shares',
    avgCost: 'Avg Cost',
    sharesPlaceholder: 'Shares',
    costPlaceholder: 'Avg cost',
    holdingValue: 'Value',
    holdingGain: 'Gain',
    totalValue: 'Portfolio Value',
    totalGain: 'Total Gain',
    noHoldings: 'No position — set the shares and average cost.',
  },

  calendario: {
    lead: 'Book a 30-minute conversation with me. Sign in with your email — you get a code, no password — and pick a free time. Times are Lisbon time.',
    month: 'Month',
    day: 'Day',
    today: 'Today',
    prev: 'Previous month',
    next: 'Next month',
    free: 'free',
    frees: 'free',
    noSlots: 'No free times on this day.',
    pickDay: 'Pick a day with free times.',
    signIn: 'Sign in',
    signInHint: 'Only signed-in people see availability. The code goes to your email; there is no password.',
    email: 'Email',
    sendCode: 'Send code',
    code: 'Code',
    codeHint: 'Six digits, sent to your email. Valid for ten minutes.',
    verify: 'Sign in',
    resend: 'Send another',
    signedAs: 'Signed in as',
    signOut: 'Sign out',
    bookTitle: 'New meeting',
    titleLabel: 'Subject',
    titlePlaceholder: 'What you want to talk about',
    noteLabel: 'Notes',
    notePlaceholder: 'Context, links, whatever helps.',
    confirm: 'Book',
    cancel: 'Cancel',
    mine: 'Your meetings',
    none: 'Nothing booked yet.',
    cancelMeeting: 'Cancel meeting',
    cancelled: 'Meeting cancelled.',
    booked: 'Booked. I sent you a confirmation by email.',
    sending: 'Sending…',
    tz: 'Lisbon time',
    minutes: 'min',
    errors: {
      email: 'That email does not look right.',
      code: 'Wrong or expired code.',
      limit: 'Too many attempts. Wait a bit.',
      taken: 'That time is no longer free.',
      off: 'Booking is switched off right now. Email me instead.',
      generic: 'That did not work. Try again.',
    },
  },

  sobre: {
    lead: 'Software engineer in Barcelos. I build products with language models inside them.',
    specs: 'Specifications',
    specRole: 'Role',
    specPlace: 'Location',
    specCompany: 'Company',
    specStack: 'Tooling',
    specStackValue: 'TypeScript · Python · Astro · Docker · Postgres · MCP',
    specSince: 'Coding since',
    specSinceValue: 'whenever there was a keyboard nearby',
    more: 'More about this site',
    colophon:
      'This site is an operating system. On a phone it behaves like an iPhone, on a computer like a Mac — windows you can drag, a Dock that magnifies, a Control Centre that genuinely works. It is built with Astro, HTML and CSS, with hand-written JavaScript and zero frameworks. Everything you read is plain HTML underneath: it works without JavaScript and search engines read it just the same.',
    buttonWrite: 'Write to me',
    buttonProjects: 'See projects',
  },

  escritos: {
    heading: 'Blog',
    title: 'Blog',
    description:
      'Notes by Hélder Gonçalves on software engineering, language models, agents, MCP and automation.',
    lead: 'Notes on engineering, language models and the tools I build. No schedule — only when there is something worth saying.',
    empty: 'Nothing published yet. Soon.',
    pick: 'Pick something from the list.',
    feed: 'Subscribe via RSS',
    all: 'All posts',
    count: 'pieces',
    readingTime: 'min read',
    search: 'Search',
    noMatch: 'No results',
    compose: 'Write to Hélder',
    share: 'Share',
    sidebar: 'Show or hide the list',
    updated: 'Updated on',
    readOther: 'Ler em português',
    tags: 'Topics',
    talk: 'Disagree, or want to keep the conversation going?',
    talkLink: 'Write to me.',
    backToList: '← Blog',
    subscribeTitle: 'Get new writing',
    subscribeLabel: 'Your email',
    subscribePlaceholder: 'you@email.com',
    subscribeAction: 'Subscribe',
    subscribeNote: 'One email when there is something new. Nothing else, and you can leave whenever.',
    subscribeSending: 'Sending…',
    subscribeSent: 'Almost there: confirm using the link I just emailed you.',
    subscribeBad: 'That email does not look right.',
    subscribeFail: 'That did not work. Try again in a moment.',
    subscribeOff: 'Subscribing is switched off right now.',
  },

  contacto: {
    lead: 'Email is the fastest way. I answer anything that comes with context.',
    to: 'To',
    from: 'From',
    subject: 'Subject',
    subjectValue: 'Hello Hélder',
    body: 'Message',
    placeholder: 'Write here. Sending opens your own email app with everything filled in — there is no server storing anything.',
    send: 'Send',
    sendHint: 'Opens your email app',
    elsewhere: 'Elsewhere',
    copied: 'Email copied',
    copy: 'Copy email',
    sending: 'Sending…',
    sent: 'Message sent. Thank you — I will reply soon.',
    failed: 'I could not send it from here. I opened your email app instead.',
    limit: 'That is a lot of messages from here. Try again in a bit.',
    invalid: 'I need a valid email address to reply to.',
    short: 'Write a little more — give me some context.',
    honeypot: 'Leave this field empty',
  },

  projetos: {
    lead: 'Things I built because I needed them. Almost all of it open source.',
    open: 'Open on GitHub',
    all: 'Everything on GitHub',
    list: [
      {
        name: 'Stocks app MCP',
        tagline: 'Claude reading my portfolio',
        body: 'An MCP server that reads the local database of the macOS Stocks app and hands portfolios and quotes to any model. No paid API, no scraping: the data was already on disk.',
        tags: ['MCP', 'Swift', 'macOS'],
      },
      {
        name: 'Garmin → Claude Code',
        tagline: 'Driving the laptop from a bike',
        body: 'A bridge that turns a Garmin bike computer into a remote control for Claude Code: I fire off tasks and read the result on the handlebar screen. It started as a joke and kept working.',
        tags: ['Garmin', 'TypeScript', 'Agents'],
      },
      {
        name: 'Chat → backlog',
        tagline: 'Community turned into product',
        body: 'A bot that reads a community chat, works out which messages are real requests and writes clean issues with context and priority. Less "someone mentioned this on Discord once".',
        tags: ['LLM', 'Python', 'Automation'],
      },
      {
        name: 'This site',
        tagline: 'An operating system in 60 KB',
        body: 'What you are looking at. Astro for the content, hand-written JavaScript for the windows, the Dock, the gestures and the phone inside the phone. No React, no animation library, no tracking.',
        tags: ['Astro', 'CSS', 'No frameworks'],
      },
    ],
  },

  mensagens: {
    lead: 'Quick questions, quick answers.',
    contactName: 'Hélder',
    status: 'usually replies the same day',
    placeholder: 'Pick a question…',
    input: 'Write a message…',
    send: 'Send',
    ai: 'AI-generated answers, based on what is on this site.',
    aiOff: 'Canned answers. For a real conversation, email me.',
    error: 'I could not answer just now. Try again, or email me.',
    limit: 'That is a lot of talking for today. Email me and I will reply myself.',
    unknown: 'That one is better asked directly: helder@heldergoncalves.io',
    typing: 'typing…',
    delivered: 'Delivered',
    restart: 'Start over',
    opener: 'Hello! This is me in automatic mode. Ask away — or write to me properly by email.',
    chat: [
      {
        q: 'What do you actually do?',
        a: 'I build software with language models inside it: agents that do real work, MCP servers that connect models to data that already exists, and automation that takes dull tasks off people.',
      },
      {
        q: 'Are you available for work?',
        a: 'By day I am at Bitsapiens. Outside that I always listen to projects with a realistic deadline and an interesting problem — especially anything involving agents, data or building a product from zero.',
      },
      {
        q: 'What tools do you use?',
        a: 'TypeScript and Python for nearly everything. Astro for sites, Docker and Coolify to ship them, Postgres when there is serious data. And a lot of Claude Code — I now write less code by hand and review a great deal more.',
      },
      {
        q: 'How was this site built?',
        a: 'Astro generates static HTML and the rest is hand-written JavaScript: draggable windows, a magnifying Dock, phone gestures. Zero frameworks. Open the Terminal and type "about" if you want the details.',
      },
      {
        q: 'Where do you write?',
        a: 'Right here, in the Blog app. There is an RSS feed and no newsletter — I would rather you came when you felt like it.',
      },
      {
        q: 'Can I email you?',
        a: 'Of course. helder@heldergoncalves.io — I answer anything that comes with context. Open the Contact app and it is already filled in.',
      },
    ],
  },

  definicoes: {
    appearance: 'Appearance',
    appearanceHint: 'Light, dark, or whatever your system asks for.',
    auto: 'Automatic',
    light: 'Light',
    dark: 'Dark',
    wallpaper: 'Wallpaper',
    wallpaperHint: 'Pick the scenery. It is remembered on this device.',
    language: 'Language',
    languageHint: 'Changes the whole site, writing included.',
    motion: 'Motion',
    motionHint: 'Turn the transitions off if you prefer the site still.',
    motionOn: 'On',
    motionOff: 'Reduced',
    sound: 'Sound',
    soundHint: 'Quiet clicks when apps open and close.',
    reset: 'Reset everything',
    resetHint: 'Back to factory settings, then reload.',
    about: 'About this system',
    version: 'Version',
    legal: 'Notice',
    legalText:
      "Personal site, non-commercial, no ads and no revenue. A homage to Apple's systems — not affiliated with Apple Inc. in any way. The Apple app icons are Apple's, obtained from public sources (see NOTICE.md); the rest are from Lucide (ISC), and the typeface outside Apple devices is Inter (OFL). Apple, iPhone and macOS are trademarks of Apple Inc.",
    wallpapers: {
      aurora: 'Aurora',
      sonoma: 'Ridge',
      night: 'Night',
      graphite: 'Graphite',
    },
  },

  terminal: {
    welcome: 'Type "help" to see what this does.',
    unknown: 'command not found:',
    hint: 'Try:',
    help: [
      ['help', 'this list'],
      ['about', 'who I am'],
      ['writing', 'list the writing'],
      ['read <n>', 'open piece number n'],
      ['projects', 'what I am building'],
      ['contact', 'how to reach me'],
      ['open <app>', 'open an application'],
      ['theme light|dark', 'change the appearance'],
      ['lang pt|en', 'change language'],
      ['date', 'what day it is'],
      ['neofetch', 'the specs of this machine'],
      ['clear', 'clear the screen'],
    ],
    sudo: 'Nice try. This user is not in the sudoers file — this incident will be reported.',
    openedApp: 'opening',
    noApp: 'no application by that name.',
    noPost: 'no piece with that number.',
  },

  notFound: {
    title: 'Page not found',
    lead: 'This address does not exist — or does not exist any more.',
    home: 'Go home',
    blog: 'Read the writing',
    code: 'Error 404',
    dialog: 'The application cannot be opened because the file was not found.',
    ok: 'OK',
  },

  labels: { github: 'GitHub', linkedin: 'LinkedIn', twitter: 'X', email: 'Email', rss: 'RSS' },
};
