// ─────────────────────────────────────────────────────────────────────
// The Finances — the Stocks app's third face, owner only. In English.
// Same keys as financas.pt.ts, exactly; copy.ts is where TypeScript
// makes sure of it.
//
// `{x}` is a value JavaScript fills in — the strings reach the browser
// as JSON (Shell.astro), and JSON carries no functions. Amounts arrive
// already formatted in the viewer's currency and language, with
// `Intl.NumberFormat`; what's decided here is only the sentence around
// them.
//
// The word "estimate" is not decoration. This is a management tool, not
// accounting and not tax advice.
// ─────────────────────────────────────────────────────────────────────

export const FINANCAS_EN = {
  face: 'Finances',
  lead: 'Management estimates. Not accounting, not tax advice.',
  disclaimer: 'An estimate. Invoices are issued at the tax portal; the accountant is who closes the books.',
  year: 'The year so far',
  pick: 'Open the year, or pick a client.',
  loading: 'Loading…',
  unavailable: "Couldn't read the finances. Try again in a moment.",
  invoiced: 'Invoiced',
  received: 'Received',
  receivedNote: 'What actually reached the account. Withholding never does.',
  goal: 'Target for the year',
  noGoal: 'No target set',
  ofGoal: '{n} of target',
  clients: 'Clients',
  noClients: 'No clients yet. Add the first one.',
  clientLine: '{faturas} invoices · {valor} this year',
  overdue: 'Overdue',
  noOverdue: 'Nothing overdue.',
  overdueCount: '{n} outstanding',
  months: 'By month',
  invoices: 'Invoices',
  projects: 'Projects',
  phases: 'Phases',
  avencas: 'Retainers',
  perMonth: '{valor} a month',
  phaseLine: '{valor} · due {data}',
  billed: 'Invoiced',
  notBilled: 'Not invoiced',
  add: 'Add',
  edit: 'Edit',
  remove: 'Remove',
  save: 'Save',
  cancel: 'Cancel',
  confirmRemove: 'Remove this, and everything that hangs off it?',
  share: 'Share with the client',
  shared: "In the client's folder",
  sharePdf: 'Choose the invoice PDF',
  shareHow: 'The real PDF, the one from the tax portal. This app does not generate invoices.',
  shareNoEmail: 'This client has no email — without one there is no folder for the invoice to land in.',
  unshare: 'Stop sharing',
  howLabel: 'Where this comes from',
  rates: 'Rates and regime',
  ratesLead: 'These change from year to year. Whatever is here is what the sums use.',
  states: {
    emitida: 'Issued',
    paga: 'Paid',
    atraso: 'Overdue',
  },
  tiles: {
    iva: 'VAT to hand over',
    retido: 'Tax withheld',
    ss: 'Social Security',
    forecast: 'Left to invoice',
    irs: 'Income tax estimate',
  },
  how: {
    iva: 'VAT at {taxa} on {base} of invoiced base.',
    ivaExempt: 'VAT exempt: {motivo}.',
    retido: 'Withholding of {taxa} on {base} invoiced. The client hands this to the state — it never reaches the account.',
    ss: '{taxa} on {relevante}, which is {fracao} of the {base} invoiced in Q{trimestre} {ano}.',
    ssExempt: 'Exempt during the first months of activity.',
    irs: 'A coefficient of {coef} on {base} gives {rendimento} of taxable income. The brackets apply to that; less {retido} already withheld.',
    irsStep: '{taxa} on {valor}',
    forecast: '{contratado} contracted in retainers and {previsto} in expected phases before year end.',
    contracted: 'Contracted',
    expected: 'Expected',
  },
  fields: {
    name: 'Name',
    email: "Client's email",
    nif: 'Tax number',
    notes: 'Notes',
    value: 'Amount',
    base: 'Base amount',
    date: 'Date',
    due: 'Due on',
    number: 'Number',
    state: 'Status',
    paidOn: 'Paid on',
    client: 'Client',
    project: 'Project',
    avenca: 'Retainer',
    expected: 'Expected date',
    monthly: 'Monthly amount',
    day: 'Day of the month',
    begins: 'Starts',
    ends: 'Ends',
    none: 'None',
    iva: 'VAT',
    ivaExempt: 'Exempt under article 53',
    ivaReason: 'Reason for the exemption',
    retencao: 'Withholding tax',
    retencaoWaived: 'Withholding waived',
    coeficiente: 'Simplified regime coefficient',
    ssTaxa: 'Social Security rate',
    ssBase: 'Share of invoicing that counts',
    ssMonths: 'Exempt months at the start',
    start: 'Activity start date',
    goal: 'Target for the year',
  },
  errors: {
    generic: "That didn't work. Try again.",
    dados: 'Something is missing.',
    email: "That email doesn't look like one.",
    estado: 'No such status.',
    taxa: 'A rate is a fraction: 0.23, not 23.',
    pdf: 'PDF only — the one from the tax portal.',
    cheio: "The client's folder is full.",
    limite: 'Easy. Try again shortly.',
    inexistente: "That's gone.",
    sessao: 'The session ended. Sign in again.',
    dono: 'Owner only.',
  },
};
