// ─────────────────────────────────────────────────────────────────────
// O texto do sistema em inglês: a barra de menus, os menus, a Central de
// Controlo, os widgets, o ecrã bloqueado. É `COPY.en.os`; vive à parte
// porque é a maior das secções, e o ficheiro de língua tem um tecto.
// ─────────────────────────────────────────────────────────────────────
export const OS_EN = {
  macName: 'helderOS',
  phoneName: 'iHelder',
  booting: 'Starting up',
  greeting: 'Hello',
  unlock: 'Swipe up to open',
  unlockShort: 'Swipe up',
  lockHint: 'Tap or swipe up',
  welcome: 'Welcome',
  openApp: 'Open',
  close: 'Close',
  aboutApp: 'About %s',
  minimize: 'Minimise',
  zoom: 'Full screen',
  back: 'Back',
  done: 'Done',
  search: 'Search',
  searchHint: '↩ to open · esc to close',
  searchApps: 'Applications',
  searchPosts: 'Blog',
  searchLinks: 'Links',
  searchEmpty: 'No results',
  noWindows: 'No windows open. Pick something from the Dock.',
  trash: 'Trash',
  trashEmpty: 'The Trash is empty. As it should be.',
  desktopHd: "Hélder's Disk",
  desktopCv: 'Résumé.pdf',
  hintMac: 'Drag the windows · ⌘K to search',
  hintPhone: 'Tap an icon · swipe up to go home',
  appSwitcher: 'Open apps',
  notifications: 'Notifications',
  wallpaperNames: { aurora: 'Aurora', sonoma: 'Ridge', night: 'Night', graphite: 'Graphite' },
  today: 'Today',
  widgets: {
    title: 'Widgets',
    add: 'Add Widget',
    edit: 'Edit Widgets…',
    done: 'Done',
    remove: 'Remove widget',
    hint: 'Touch and hold the Home Screen to edit.',
    names: { date: 'Calendar', clock: 'Clock', post: 'Latest post', list: 'Posts', links: 'Links' },
  },
  wifiOn: 'Wi‑Fi: On',
  networkSettings: 'Network Settings…',
  batteryLevel: 'Battery: %s %',
  batteryCharging: 'Charging',
  batterySource: 'Power Source: Power Adapter',
  dockShow: 'Show',
  dockOpen: 'Open',
  dockClose: 'Quit',
  menus: {
    apple: [
      { label: 'About This Mac', action: 'open:sobre' },
      { label: 'System Settings…', action: 'open:definicoes' },
      { label: '—', action: '' },
      { label: 'Sign In…', action: 'entrar' },
      { label: '—', action: '' },
      { label: 'Write to Hélder…', action: 'mail' },
      { label: 'GitHub', action: 'link:github' },
      { label: '—', action: '' },
      { label: 'Restart…', action: 'restart' },
    ],
    file: [
      { label: 'Open…', action: 'spotlight', key: '⌘O' },
      { label: '—', action: '' },
      { label: 'Close Window', action: 'close', key: '⌘W' },
      { label: 'Close All', action: 'closeAll', key: '⌥⌘W' },
    ],
    edit: [
      { label: 'Copy Link', action: 'copy', key: '⇧⌘C' },
      { label: 'Share…', action: 'share' },
      { label: '—', action: '' },
      { label: 'Find…', action: 'spotlight', key: '⌘K' },
    ],
    view: [
      { label: 'Toggle Appearance', action: 'theme' },
      { label: 'Next Wallpaper', action: 'wallpaper:next' },
      { label: '—', action: '' },
      { label: 'Enter Full Screen', action: 'zoom', key: '⌃⌘F' },
    ],
    control: [
      { label: 'Appearance', action: 'theme' },
      { label: 'Wallpaper', action: 'wallpaper:next' },
      { label: 'Language', action: 'lang' },
      { label: '—', action: '' },
      { label: 'System Settings…', action: 'open:definicoes' },
    ],
    window: [
      { label: 'Minimise', action: 'minimize', key: '⌘M' },
      { label: 'Full screen', action: 'zoom' },
      { label: 'Close window', action: 'close', key: '⌘W' },
      { label: '—', action: '' },
      { label: 'Open apps…', action: 'switcher', key: '⌘⇥' },
      { label: 'Tile windows', action: 'tile' },
      { label: 'Close everything', action: 'closeAll' },
    ],
    help: [
      { label: 'Search…', action: 'spotlight', key: '⌘K' },
      { label: 'Switch to Portuguese', action: 'lang' },
      { label: 'Switch theme', action: 'theme' },
      { label: '—', action: '' },
      { label: 'How this was built', action: 'open:sobre' },
    ],
  },
  // Only what each app adds or overrides on top of the generic menus
  // above — anything missing here falls back to the generic one, just
  // like on real macOS.
  appMenus: {
    escritos: {
      file: [
        { label: 'New post…', action: 'mail' },
        { label: '—', action: '' },
        { label: 'Close window', action: 'close', key: '⌘W' },
      ],
      edit: [
        { label: 'Copy link', action: 'copy', key: '⇧⌘C' },
        { label: '—', action: '' },
        { label: 'Search…', action: 'spotlight', key: '⌘K' },
      ],
      view: [
        { label: 'Show or hide folders', action: 'toggleSidebar' },
        { label: '—', action: '' },
        { label: 'Full screen', action: 'zoom', key: '⌃⌘F' },
      ],
    },
    mensagens: {
      file: [
        { label: 'New message…', action: 'mail' },
        { label: '—', action: '' },
        { label: 'Close window', action: 'close', key: '⌘W' },
      ],
    },
    terminal: {
      edit: [
        { label: 'Copy', action: 'copy', key: '⌘C' },
        { label: '—', action: '' },
        { label: 'Search…', action: 'spotlight', key: '⌘K' },
      ],
    },
    definicoes: {
      view: [
        { label: 'Switch theme', action: 'theme' },
        { label: 'Change wallpaper', action: 'wallpaper:next' },
      ],
    },
  },
  menuLabels: { file: 'File', edit: 'Edit', view: 'View', window: 'Window', help: 'Help' },
  copied: 'Link copied',
  control: {
    title: 'Control Centre',
    theme: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    wallpaper: 'Wallpaper',
    lang: 'Language',
    brightness: 'Brightness',
    focus: 'Focus',
    focusOn: 'Essentials only',
    airplane: 'Aeroplane mode',
    wifi: 'Wi‑Fi',
    offline: 'Offline — the site still works.',
  },
  battery: 'Battery',
  wifi: 'Wi‑Fi',
  entrar: {
    title: 'Sign In',
    guest: 'Guest',
    signIn: 'Sign In',
    signedInAs: 'Signed in as',
    continue: 'Continue',
  },
};
