// ─────────────────────────────────────────────────────────────────────
// O texto do sistema em português: a barra de menus, os menus, a Central de
// Controlo, os widgets, o ecrã bloqueado. É `COPY.pt.os`; vive à parte
// porque é a maior das secções, e o ficheiro de língua tem um tecto.
// ─────────────────────────────────────────────────────────────────────
export const OS_PT = {
  macName: 'helderOS',
  phoneName: 'iHelder',
  booting: 'A arrancar',
  greeting: 'Olá',
  unlock: 'Deslizar para abrir',
  unlockShort: 'Deslizar',
  lockHint: 'Toca ou desliza para cima',
  welcome: 'Bem-vindo',
  openApp: 'Abrir',
  close: 'Fechar',
  aboutApp: 'Acerca de %s',
  minimize: 'Minimizar',
  zoom: 'Ecrã inteiro',
  back: 'Voltar',
  done: 'Concluído',
  search: 'Pesquisar',
  searchHint: '↩ para abrir · esc para fechar',
  searchApps: 'Aplicações',
  searchPosts: 'Blog',
  searchLinks: 'Ligações',
  searchEmpty: 'Sem resultados',
  noWindows: 'Nenhuma janela aberta. Escolhe uma aplicação na Dock.',
  trash: 'Reciclagem',
  trashEmpty: 'A Reciclagem está vazia. Como deve ser.',
  desktopHd: 'Disco de Hélder',
  desktopCv: 'Currículo.pdf',
  hintMac: 'Arrasta as janelas · ⌘K para pesquisar',
  hintPhone: 'Toca num ícone · desliza para cima para voltar',
  appSwitcher: 'Aplicações abertas',
  notifications: 'Notificações',
  wallpaperNames: { aurora: 'Aurora', sonoma: 'Serra', night: 'Noite', graphite: 'Grafite' },
  today: 'Hoje',
  widgets: {
    title: 'Widgets',
    add: 'Adicionar widget',
    edit: 'Editar widgets…',
    done: 'Concluído',
    remove: 'Remover widget',
    hint: 'Mantém o dedo no ecrã inicial para editar.',
    names: { date: 'Calendário', clock: 'Relógio', post: 'Último escrito', list: 'Escritos', links: 'Ligações' },
  },
  wifiOn: 'Wi‑Fi: ligado',
  networkSettings: 'Definições de rede…',
  batteryLevel: 'Bateria: %s %',
  batteryCharging: 'A carregar',
  batterySource: 'Fonte de alimentação: adaptador',
  dockShow: 'Mostrar',
  dockOpen: 'Abrir',
  dockClose: 'Fechar',
  menus: {
    apple: [
      { label: 'Sobre este Mac', action: 'open:sobre' },
      { label: 'Definições do Sistema…', action: 'open:definicoes' },
      { label: '—', action: '' },
      { label: 'Entrar…', action: 'entrar' },
      { label: '—', action: '' },
      { label: 'Escrever ao Hélder…', action: 'mail' },
      { label: 'GitHub', action: 'link:github' },
      { label: '—', action: '' },
      { label: 'Reiniciar…', action: 'restart' },
    ],
    file: [
      { label: 'Abrir…', action: 'spotlight', key: '⌘O' },
      { label: '—', action: '' },
      { label: 'Fechar janela', action: 'close', key: '⌘W' },
      { label: 'Fechar tudo', action: 'closeAll', key: '⌥⌘W' },
    ],
    edit: [
      { label: 'Copiar ligação', action: 'copy', key: '⇧⌘C' },
      { label: 'Partilhar…', action: 'share' },
      { label: '—', action: '' },
      { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
    ],
    view: [
      { label: 'Mudar o tema', action: 'theme' },
      { label: 'Mudar o fundo', action: 'wallpaper:next' },
      { label: '—', action: '' },
      { label: 'Ecrã inteiro', action: 'zoom', key: '⌃⌘F' },
    ],
    control: [
      { label: 'Aparência', action: 'theme' },
      { label: 'Fundo', action: 'wallpaper:next' },
      { label: 'Idioma', action: 'lang' },
      { label: '—', action: '' },
      { label: 'Definições do Sistema…', action: 'open:definicoes' },
    ],
    window: [
      { label: 'Minimizar', action: 'minimize', key: '⌘M' },
      { label: 'Ecrã inteiro', action: 'zoom' },
      { label: 'Fechar janela', action: 'close', key: '⌘W' },
      { label: '—', action: '' },
      { label: 'Aplicações abertas…', action: 'switcher', key: '⌘⇥' },
      { label: 'Arrumar janelas', action: 'tile' },
      { label: 'Fechar tudo', action: 'closeAll' },
    ],
    help: [
      { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
      { label: 'Mudar para inglês', action: 'lang' },
      { label: 'Mudar o tema', action: 'theme' },
      { label: '—', action: '' },
      { label: 'Como isto foi feito', action: 'open:sobre' },
    ],
  },
  // Só o que cada app acrescenta ou substitui aos menus genéricos
  // acima — o que faltar aqui cai no genérico, tal como no macOS real.
  appMenus: {
    escritos: {
      file: [
        { label: 'Novo escrito…', action: 'mail' },
        { label: '—', action: '' },
        { label: 'Fechar janela', action: 'close', key: '⌘W' },
      ],
      edit: [
        { label: 'Copiar ligação', action: 'copy', key: '⇧⌘C' },
        { label: '—', action: '' },
        { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
      ],
      view: [
        { label: 'Mostrar ou ocultar pastas', action: 'toggleSidebar' },
        { label: '—', action: '' },
        { label: 'Ecrã inteiro', action: 'zoom', key: '⌃⌘F' },
      ],
    },
    mensagens: {
      file: [
        { label: 'Nova mensagem…', action: 'mail' },
        { label: '—', action: '' },
        { label: 'Fechar janela', action: 'close', key: '⌘W' },
      ],
    },
    terminal: {
      edit: [
        { label: 'Copiar', action: 'copy', key: '⌘C' },
        { label: '—', action: '' },
        { label: 'Pesquisar…', action: 'spotlight', key: '⌘K' },
      ],
    },
    definicoes: {
      view: [
        { label: 'Mudar o tema', action: 'theme' },
        { label: 'Mudar o fundo', action: 'wallpaper:next' },
      ],
    },
  },
  menuLabels: { file: 'Ficheiro', edit: 'Editar', view: 'Ver', window: 'Janela', help: 'Ajuda' },
  copied: 'Ligação copiada',
  control: {
    title: 'Central de Controlo',
    theme: 'Aparência',
    light: 'Claro',
    dark: 'Escuro',
    wallpaper: 'Fundo',
    lang: 'Idioma',
    brightness: 'Brilho',
    focus: 'Concentração',
    focusOn: 'Só o essencial',
    airplane: 'Modo avião',
    wifi: 'Wi‑Fi',
    offline: 'Sem rede — o site continua a funcionar.',
  },
  battery: 'Bateria',
  wifi: 'Wi‑Fi',
  entrar: {
    title: 'Entrar',
    guest: 'Visitante',
    signIn: 'Entrar',
    signedInAs: 'Sessão iniciada como',
    continue: 'Continuar',
  },
};
